import type { Metadata } from "next";
import "./globals.scss";


export const metadata: Metadata = {
  title: "Andrii Topii | Сайти для бізнесу, лендінги, Web-застосунки під ключ",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk" >
      <body>
        
        {children}

       
      </body>
    </html>
  );
}
